### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by IRDjangoDeveloper** [emmakodes/ocrandsummarize#1]
hello sir.
i cloned and install your project on my windows.
but script is not working right for me.
im trying to ocred one image on your pythonanywhere and my localhost.
your pythonanywhere is working fine, but my django project show this error:

check your filename and ensure it doesn't have any space or check if it has any text

please help me to fix this problem

**Comment by emmakodes** [comment]
ok, I will clone and run to see what is happening

**Comment by emmakodes** [comment]
This error is because tesseract is not installed on your computer.

If you are using Ubuntu install tesseract using following command:

sudo apt-get install tesseract-ocr

For mac:

brew install tesseract

check out this link for more solution on window system:
https://stackoverflow.com/questions/50951955/pytesseract-tesseractnotfound-error-tesseract-is-not-installed-or-its-not-i

If you have any issue while doing this, pls do reach me

**Comment by IRDjangoDeveloper** [comment]
> This error is because tesseract is not installed on your computer.
> 
> If you are using Ubuntu install tesseract using following command:
> 
> sudo apt-get install tesseract-ocr
> 
> For mac:
> 
> brew install tesseract
> 
> check out this link for more solution on window system:
> https://stackoverflow.com/questions/50951955/pytesseract-tesseractnotfound-error-tesseract-is-not-installed-or-its-not-i
> 
> If you have any issue while doing this, pls do reach me

Tnx bro
